# Generated by Django 5.1.7 on 2025-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
