# Generated by Django 5.1.7 on 2025-04-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hoteluser_latitude_hoteluser_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='json_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_uploads', to='user.hoteluser')),
            ],
        ),
    ]
